### ISSUE TITLE
16 colors setting removed still in README.md

### ISSUE THREAD

**Issue by kwbr** [lifepillar/vim-solarized8#104]
I've used `g:solarized_use16` to use my Terminal colors configured with the solarized color scheme (iTerm2 builtin). It seems it was removed before and then readded: https://github.com/lifepillar/vim-solarized8/commit/de124fa1ea300b02daa0a17219a77d959b5f25d4

Did the original reason changed?

For now I `set t_Co=16` in vim to force 16 colors. Is this the way to go? If yes, you should remove it also from the README.md

Thanks for you work, btw. Highly appreciated.

**Comment by lifepillar** [comment]
Yes, ideally you should set `t_Co` to tell Vim how many colors are available. Now, re-reading https://github.com/lifepillar/vim-solarized8/commit/de124fa1ea300b02daa0a17219a77d959b5f25d4 and https://github.com/lifepillar/vim-solarized8/issues/71, it seems that it is not possible in Neovim. The current code does not support `g:solarized_use16`, though. Let me check the commit history to understand what's happened. I'll report back.

**Comment by lifepillar** [comment]
Ok, it was removed in a9e5707be04d41664af97b3252337e191b90362e when I upgraded to Colortemplate v3 syntax. I had forgotten the reason it was there.

This is a bit of a problem because Colortemplate currently generates code that checks directly `t_Co` (vs setting a script variable based on that setting, which could be overriden). Such change was made recently in response to [a suggestion by Vim's author](https://github.com/vim/vim/issues/12408#issuecomment-1569154289) that the code for Vim's colorschemes could be simplified.

Now, the change is not set in stone. But upon reflection, I think that a colorscheme's option is a hack. It's important to clarify Neovim's design choices here. Since Neovim's `t_Co` is read-only, the logical consequence is that, in Neovim's philosophy, it's the terminal that should be configured if the user wants to use the terminal's ANSI colors (or maybe Neovim has another mechanism, which I don't know). Forcing Neovim to use 16 colors when other parts of the system (e.g., `t_Co`) say otherwise may potentially lead to subtle bugs.

So, my tentative answer to your question would be: in Vim yes, just set `t_Co`; for Neovim, find a way for your terminal to report 16 colors.

Anyway, I am open to discussing this. Perhaps, the best thing to do is ask Neovim's developers what the recommended way to tell Neovim to use the terminal's 16 ANSI colors is.

**Comment by lifepillar** [comment]
Browsing through Neovim's repo, the most relevant thread seems to be this: https://github.com/neovim/neovim/issues/11974. In which, essentially they say that the colorscheme should be defined to use the appropriate colors.

So, basically my understanding is that Neovim colorschemes should not use `t_Co`. It's probably wise at this point to have a Neovim-dedicated branch, rather than trying to reconcile those differences.
