### ISSUE TITLE
MatchParen highlighting inverts colors of bracket, makes it look like cursor has jumped to matching bracket

### ISSUE THREAD

**Issue by insidewhy** [lifepillar/vim-solarized8#11]
At least in solarized-light this behaviour is really confusing.

Instead of:

```
hi! MatchParen cterm=NONE,bold gui=NONE,bold ctermfg=15 guifg=#fdf6e3 ctermbg=12 guibg=#839496
```

Switching the fg and bg looks much better:

```
hi! MatchParen cterm=NONE,bold gui=NONE,bold ctermbg=15 guibg=#fdf6e3 ctermfg=12 guifg=#839496
```

It highlights the other bracket without making it look like the cursor has jumped.

**Comment by lifepillar** [comment]
I agree that the current colors may be confusing. But, IMHO, with your suggestion the matching parenthesis does not stand out. How about this instead:

```vim
hi! MatchParen cterm=NONE,bold gui=NONE,bold  guibg=#eee8d5 guifg=NONE
```

This would not change the color of the parenthesis (try it on a `vim` file, where parentheses are red), and use a slightly darker background instead of the original grey.

**Comment by insidewhy** [comment]
Your suggestion is what I ultimately wanted, I gave up because I am lazy ;) It worked though because you did the work for me, go laziness! And thanks ;)
