### ISSUE TITLE
Javascript function name has no colour

### ISSUE THREAD

**Issue by hadiwina** [lifepillar/vim-solarized8#2]
Hello,

Great color scheme. I'm using the flat version now.

Just curious if there is any good way to highlight the function/method names in javascript with a colour. 

![screen shot 2016-09-27 at 5 55 10 pm](https://cloud.githubusercontent.com/assets/5366783/18893379/aa6abe70-84db-11e6-83ac-70e3d2818f0a.png)

![screen shot 2016-09-27 at 5 55 47 pm](https://cloud.githubusercontent.com/assets/5366783/18893384/afc236b4-84db-11e6-9a37-c8980f380d0e.png)

The first screenshot is with the ES2015 syntax.

Any tips on how to do this?

Thanks!

**Comment by lifepillar** [comment]
What filetype are you using (`se filetype?`)?

**Comment by hadiwina** [comment]
```
filetype=javascript
```

is what I have.

**Comment by lifepillar** [comment]
There is no highlight group associated to function/method names in that filetype, so those parts cannot be highlighted by a colorscheme.

I suggest that you contact the author of the JavaScript scripts in Vim (`:e $VIMRUNTIME/syntax/javascript.vim`) or look for some plugin that extends JavaScript highlighting.

Closing because this is not an issue that can be solved in the color scheme.

**Comment by hadiwina** [comment]
Thank you!
