### ISSUE TITLE
A question about project and its source!

### ISSUE THREAD

**Issue by ghost** [lifepillar/vim-solarized8#34]
Hi.
At the first step I should thank you for this good theme.
Actually my question is: Is this vim-colorscheme associate with [this](https://github.com/altercation/vim-colors-solarized) colorscheme (forked from it, inspired idea from it, relation with colors and values, etc.)? & Which one is really better?
Good luck.

**Comment by lifepillar** [comment]
Yes, this project was forked from the original Solarized. You may read about that in the [first commit](https://github.com/lifepillar/vim-solarized8/commit/916b9b0302e6b08d31d30b446a2323367256bcd9). Over time, though, the code has been completely re-written (recently, I have moved to use my own [Colortemplate](https://github.com/lifepillar/vim-colortemplate) plugin), so currently the code bears no relationship with the original project.

As stated in the Readme, the color palette is exactly the same as in Solarized, but I have modified the appearance of a few highlight groups (for the better, IMHO), e.g., matching parentheses, cursors, tab lines, etc…  Overall, the look is still pretty similar to the original version.

As for which colorscheme is “better”, that is largely a subjective judgement. And if you ask *me*, the answer should be obvious :) The main differences may be summarised as follows:

- this project supports true-color terminals;
- this project is actively maintained;
- this project retains the three original Solarized variants (normal, high contrast, low contrast), but also adds a new “flat” variant (see screenshots in the Readme);
- this project removes a few bell-and-whistles, like menu entries for GUI Vim.

I would also say that, since it is now based on Colortemplate, this colorscheme is easier to tweak to your taste, shouldn't you like something.

**Comment by ghost** [comment]
A great answer and a great theme, Uh-huh shouldn't I use this color-scheme instead of any other color-schemes!!! :D 
Thanks for answer and hope this project be actively maintaining in the future.
Regards.
