### ISSUE TITLE
cost of g:solarized_extra_hi_groups=0

### ISSUE THREAD

**Issue by bam80** [lifepillar/vim-solarized8#59]
Thanks for the scheme.
Could you please explain what we actually sacrifice if keep those "Solarized filetype-specific syntax highlighting groups"(whatever it means) disabled?

**Comment by lifepillar** [comment]
The original Solarized defines many additional highlight groups for specific filetypes. In Solarized 8, you can find them in `templates/_extra.colortemplate`. For example, in HTML buffers, dark Solarized defines `htmlTag` to use `#586e75` as foreground color, while`htmlTag` by default would use `#268bd2`. So, if you enable filetype-specific highlight groups, you will see slightly different colors for some filetypes. If you don't, you will just see the default ones (i.e., those specified by the corresponding filetype plugins). Such adjustments were likely proposed by users of the colorscheme (“look, the colorscheme looks fine everywhere, except that I would prefer HTML tags using this color rather than that”). Since Solarized has a huge community, with time a lot of tweaks were added.

Unfortunately, defining filetype-specific highlight groups in a colorscheme may [leave a wave of destruction when switching](https://github.com/altercation/solarized/issues/102) to another colorscheme. For this reason, in my fork they are disabled by default; they may be enabled for backward compatibility and for users who don't care (e.g., because they use Solarized exclusively).

**Comment by bam80** [comment]
Many thanks for the explanation!

Can it be the case that those adjustments are needed due nature of the scheme, or it just huge community which matters?
E.g., in standard scheme I never saw any inconsistencies I would like to fix

**Comment by lifepillar** [comment]
Mostly just personal taste, e.g., some people like more colorful syntax highlighting in Git commit buffers.

My suggestion is that if you want to override a colorscheme’s choice of colors for some filetype, do it in your own configuration or ask the maintainer of the filetype’s plugin.

**Comment by lifepillar** [comment]
And no, I think the colorscheme looks fine for most, if not all, filetypes. Of course, if you live, say, in pandoc buffers, you may see room for improvement. But adding filetype-specific tweaks in a colorscheme is not the correct solution (at least, it is not currently supported by Vim).

The issue I’ve linked to above has been discussed in Vim’s mailing list as well. I don’t recall the details, but if you search hard enough, you’ll find some interesting discussions.

**Comment by bam80** [comment]
Yes, I saw the linked issue, but it is too long to read it all.
Am I understand right those filetype-specific tweaks was maybe mesdesign from the beginning in Solarized scheme? But since the issue is still open, probably Solarized author is not fully agree with that..
Anyway, I think this issue here is resolved enough, so we can close it.
Thanks!

**Comment by lifepillar** [comment]
Yes, it is a mis-design in the sense that it is not really well supported by Vim (some argue that it is Vim that should be fixed). As for the linked issue being still open: AFAICS, Solarized is not in active development any longer.

Anyway, happy Vimming!
