### ISSUE TITLE
Last update broke reversed foreground/background.

### ISSUE THREAD

**Issue by thekaganugur** [lifepillar/vim-solarized8#64]
![2019-05-07-1557222185](https://user-images.githubusercontent.com/28161197/57290498-3108b300-70c6-11e9-97d7-07f94e48b965.png)

Problem can be seen from picture. Normally background is normal solarized color and the circle is red. But it's reversed now with latest update.

**Comment by lifepillar** [comment]
The change you are referring to was in response to issue https://github.com/lifepillar/vim-solarized8/issues/63. How do you reproduce your issue? For example, Neomake does not seem to be affected:

<img width="91" alt="image" src="https://user-images.githubusercontent.com/1193314/57308402-979dc900-70e6-11e9-98ec-f8aff3556349.png">

**Comment by lifepillar** [comment]
I have taken a look at a few other colorschemes. Vim's default colorscheme has a red background for `Error`, and many popular colorschemes do that as well (e.g., Gruvbox). But that is not universal: several colorschemes, even among those distributed with Vim, do not assign a different background to `Error`.

This and https://github.com/lifepillar/vim-solarized8/issues/63 cannot be solved at the same time. So, it's a matter of making a decision: keep or revert https://github.com/lifepillar/vim-solarized8/commit/c81e287b9d7c3e2ffe9208b1c0371bc94e61a61f?

I have no strong opinion. In favor of keeping the change:

- it is consistent with the default colorscheme and other popular colorschemes;
- solves https://github.com/lifepillar/vim-solarized8/issues/63.

In favor of reverting:

- does not break backward compatibility with Solarized;
- solves this issue.

None of these is a particularly strong argument.

@fladd I am wondering whether the whitespace mistakes mentioned in https://github.com/lifepillar/vim-solarized8/issues/63 could be marked with some symbol rather than using just spaces, so that the background would not really matter.

@kgnugur I am wondering whether the highlighting in your picture (from some plugin?) could be changed with some option (of such plugin).

**Comment by thekaganugur** [comment]
Sorry for the late response.
I'm using '/w0rp/ale'  for diagnoses in the gutter.

**Comment by fladd** [comment]
I obviously would argue for keeping the change, since the idea of solarized8 is to improve on the original solarized.
For me it would also not be a big deal if you revert it, I would just change it in my vimrc, but for Python coders who switch to the theme it might be a bit frustrating to not see white space errors, even when they explicitly set `let python_space_error_highlight=1`, since the default Python syntax that ships with Vim links space errors to the `Error` group.

**Comment by lifepillar** [comment]
@kgnugur You may link `AleErrorSign` to `Special`, `Todo` or `Title`. For instance, you may put this in your `vimrc`:

```vim
hi! link AleErrorSign Special
```
