### ISSUE TITLE
Error highlighting should not recolor the whole word

### ISSUE THREAD

**Issue by alexpolozov** [lifepillar/vim-solarized8#65]
After switching to this theme, I noticed that error highlighting seems to highlight the whole word (as opposed to just the squiggly line). Most themes, including the original Solarized, keep the word color unchanged, and only color its squiggly underline. Would it be possible to revert this or make an option for it?

See, for example, here. The word "subtrees" is not in the dictionary, so spellcheck underlines it with a warning. However, I don't want every such word to be colored purple, it's very distracting. Just the purple underlines would be enough.
![image](https://user-images.githubusercontent.com/852687/57819800-dbc04780-773e-11e9-96cb-b685c1bf1082.png)

**Comment by lifepillar** [comment]
That change is intentional and was introduced in 1e0edf58ae9d2d886aa15c912d5b10e799489068. The reason is that there are systems where no undercurl or underline is available, so one may only rely on colors to distinguish badly spelled words.

But it may be possible to detect whether underlined text is supported, e.g., using the value of `t_us` and `t_ue`. I will take a look: I'd rather have the colorscheme detect this automatically rather than introducing yet another option, if possible.

In the meantime, as a workaround you may put this in your `vimrc`:

```vim
hi SpellBad ctermfg=NONE guifg=NONE
```

(and possibly similar commands for `SpellCap`, `SpellLocal` and `SpellRare`) after loading the colorscheme.

**Comment by alexpolozov** [comment]
The workaround works, thank you!
Automatically detecting whether underlines are supported would be the best solution, if possible. I'll keep the issue open for now – please close it if you implement this fix or decide it's not worth it.

**Comment by lifepillar** [comment]
I did some research and I have concluded that it shouldn't be possible to detect support for underlining reliably, so the proposed workaround is the way to go. Hence, I am closing this.
