### ISSUE TITLE
Wrong colours in Vimr

### ISSUE THREAD

**Issue by assistcontrol** [lifepillar/vim-solarized8#67]
Vimr (https://github.com/qvacua/vimr) is a Neovim GUI for macOS. With yesterday's changes, the colours are all wrong. Console nvim works fine.

<img width="1062" alt="vimr" src="https://user-images.githubusercontent.com/2219761/59110036-76a1e100-88fb-11e9-9536-b7377d5a1436.png">

**Comment by lifepillar** [comment]
Have you tried `set termguicolors`? Or is `termguicolors` already set?

**Comment by assistcontrol** [comment]
`termguicolors` is already set.

**Comment by lifepillar** [comment]
Colors look right after I set `termguicolors`. You may need to reload the color scheme.

**Comment by assistcontrol** [comment]
Sorry, I don't understand what you mean by reload the colour scheme. Every time I start up Vimr, I get the wrong colours.

**Comment by lifepillar** [comment]
Type `:colo solarized8`. Or put this in your `vimrc`:

```vim
set termguicolors
colo solarized8
```

**Comment by lifepillar** [comment]
In VimR, `has('gui_running')` returns `0`; on the other hand, `t_Co` is undefined. Under such conditions, the current version of Solarized 8 assumes that it's running in a terminal not capable of displaying colors, and it falls back to a b&w color scheme (which sets only `term` entries).

AFAICS, VimR uses only `guifg` and `guibg` to set colors and ignores `ctermfg` and `ctermbg`. So, you *must* set `termguicolors`.

I'd also say that VimR is lying, because `has('gui_running')` should return `1`, IMO.

**Comment by assistcontrol** [comment]
Thank you, @lifepillar. You're completely right, of course. The problem was that I was setting

```vim
colo solarized8_high
set termguicolors
```

I see now that `termguicolors` has to be set _before_ choosing the colorscheme.

**Comment by lifepillar** [comment]
Thanks for the feedback. I have added a note in the Readme about this.

**Comment by StarryLeo** [comment]
@lifepillar  
The same problem also occurs in terminal vim after commit [97110ed](https://github.com/lifepillar/vim-solarized8/commit/97110edfc1ea68008783be4e91c1743436123e6d) (using WSL and [wsl-terminal](https://github.com/goreliu/wsl-terminal)):

![snipaste20190608_144624](https://user-images.githubusercontent.com/25200758/59143376-1004ec00-89fd-11e9-8695-991df40c227e.png)

![snipaste20190608_144844](https://user-images.githubusercontent.com/25200758/59143545-198f5380-89ff-11e9-98b2-1c79722c9a14.png)

**Comment by lifepillar** [comment]
Could you please report the output of the following commands when running `vim --clean`?

```vim
:echo exists('&t_Co')
:echo &t_Co
:echo &termguicolors
:echo has('gui_running')
```

Also, what's the output of `infocmp -C xterm` in the terminal?

**Comment by StarryLeo** [comment]
```
:echo exists('&t_Co')
1
:echo &t_Co
256
:echo &termguicolors
0
:echo has('gui_running')
0
```

```
infocmp -C xterm

#       Reconstructed via infocmp from file: /lib/terminfo/x/xterm
# (untranslatable capabilities removed to fit entry within 1023 bytes)
xterm|xterm-debian|X11 terminal emulator:\
        :am:bs:km:mi:ms:xn:\
        :co#80:it#8:li#24:\
        :AL=\E[%dL:DC=\E[%dP:DL=\E[%dM:DO=\E[%dB:IC=\E[%d@:\
        :K2=\EOE:LE=\E[%dD:RI=\E[%dC:SF=\E[%dS:SR=\E[%dT:\
        :UP=\E[%dA:ae=\E(B:al=\E[L:as=\E(0:bl=^G:bt=\E[Z:cd=\E[J:\
        :ce=\E[K:cl=\E[H\E[2J:cm=\E[%i%d;%dH:cr=\r:\
        :cs=\E[%i%d;%dr:ct=\E[3g:dc=\E[P:dl=\E[M:do=\n:ec=\E[%dX:\
        :ei=\E[4l:ho=\E[H:im=\E[4h:is=\E[!p\E[?3;4l\E[4l\E>:\
        :k1=\EOP:k2=\EOQ:k3=\EOR:k4=\EOS:k5=\E[15~:k6=\E[17~:\
        :k7=\E[18~:k8=\E[19~:k9=\E[20~:kD=\E[3~:kI=\E[2~:kN=\E[6~:\
        :kP=\E[5~:kb=\177:kd=\EOB:ke=\E[?1l\E>:kh=\EOH:kl=\EOD:\
        :kr=\EOC:ks=\E[?1h\E=:ku=\EOA:le=^H:mb=\E[5m:md=\E[1m:\
        :me=\E[0m:mh=\E[2m:mm=\E[?1034h:mo=\E[?1034l:mr=\E[7m:\
        :nd=\E[C:rc=\E8:sc=\E7:se=\E[27m:sf=\n:so=\E[7m:sr=\EM:\
        :st=\EH:ta=^I:te=\E[?1049l\E[23;0;0t:\
        :ti=\E[?1049h\E[22;0;0t:ue=\E[24m:up=\E[A:us=\E[4m:\
        :vb=\E[?5h\E[?5l:ve=\E[?12l\E[?25h:vi=\E[?25l:\
        :vs=\E[?12;25h:

```

**Comment by lifepillar** [comment]
I can't spot anything wrong there. With those settings, you should get the 256-color approximation of Solarized 8:

<img width="578" alt="solarized8-256colors" src="https://user-images.githubusercontent.com/1193314/59144193-3c584280-89d4-11e9-933d-44864eb17953.png">

The only thing that comes to my mind is that that terminal uses a non-standard xterm palette. To verify that, you might run [this script](https://gist.github.com/lifepillar/d4acaf918ae8d9bb2cab24d62abd768c) and compare the output with the following screenshot:

<img width="623" alt="color-cube" src="https://user-images.githubusercontent.com/1193314/59144221-cef8e180-89d4-11e9-8609-31c1a827ba3d.png">

The first of your pictures shows something unusual, however, because the status line has the right colors, while the buffer doesn't. That might happen if only some of your terminal's ANSI colors (the 16 colors you should be able to configure in your terminal's settings) are set to the Solarized palette, but it would also require Solarized 8 to use the 16-color palette, which happens only when `t_Co` is `16`. Your Vim's `t_Co` is set to `256`, however (unless you modify `t_Co` in your `vimrc`). I am a bit puzzled…

**Comment by StarryLeo** [comment]
Ok, anyway, the color looks right now.
 
![snipaste20190608_163229](https://user-images.githubusercontent.com/25200758/59144541-ec956d80-8a0b-11e9-80a3-bc5be57e1611.png)

And I found a new problem, the comment line where the cursor is located will flash:

![201906081615](https://user-images.githubusercontent.com/25200758/59144548-19e21b80-8a0c-11e9-83ca-72a8ecaecc84.gif)

**Comment by lifepillar** [comment]
>Ok, anyway, the color looks right now.

Good.

>And I found a new problem, the comment line where the cursor is located will flash:

A terminal rendering problem, perhaps? I don't see how a color scheme might affect that. If you do this:

```vim
:let g:solarized_italics=0
:colo solarized8
```

does it still flicker?

**Comment by StarryLeo** [comment]
> A terminal rendering problem, perhaps? I don't see how a color scheme might affect that. If you do this:
> 
> ```viml
> :let g:solarized_italics=0
> :colo solarized8
> ```
Thanks, it is work. I didn't realize that italic is the default now. This is indeed a problem with terminal rendering.

**Comment by lifepillar** [comment]
Good to know. Off topic: what do you use to get highlighting on hex color values?

**Comment by StarryLeo** [comment]
> Good to know. Off topic: what do you use to get highlighting on hex color values?

Use this plugins: https://github.com/ap/vim-css-color
But it has a bad point, that is, the cursor moving goes slower over those lines.

**Comment by lifepillar** [comment]
Thanks!
