### ISSUE TITLE
How to use 16-colours mode in Neovim?

### ISSUE THREAD

**Issue by lunacookies** [lifepillar/vim-solarized8#71]
Hi, I see that recently Solarized 8 was updated so that the 16-colour mode is activated using `set t_Co=16`, rather than `let g:solarized_use16 = 1`. However, Neovim does not support `t_*` settings. Is there anyway to use the 16-colour mode in Neovim?

Thanks.

**Comment by lifepillar** [comment]
If there is no way for NeoVim to determine the number of colors of the underlying terminal, I may reinstate the old option.

But I'd like to understand: did they replace `t_Co` with something else? If not, what is the rationale to remove the setting (a link would be fine)?

**Comment by lifepillar** [comment]
Using NeoVim v0.4.0 I get:

```
:echo exists('&t_Co')
1
:echo &t_Co
256
:set t_Co=16
:echo &t_Co
256
```

So, it seems like they made the setting read-only. And removed the documentation about it.

**Comment by lifepillar** [comment]
I have played with Neovim a bit, and now things are clear to me: Neovim ignores  `t_Co` and similar settings and detects terminal features automatically. Apparently, you cannot even lie to Neovim by setting the `TERM` environment variable.

I guess you want exact Solarized colors in terminals not supporting millions of colors. To achieve that in Neovim, I will need to reintroduce the old option, because Neovim always sets `t_Co` to 256.

**Comment by lunacookies** [comment]
Thank you so much!
