### ISSUE TITLE
CursorLine now an underline rather than colored

### ISSUE THREAD

**Issue by IrishPrime** [lifepillar/vim-solarized8#72]
Since commit 97110edfc1ea68008783be4e91c1743436123e6d, the `CursorLine` highlight group seems to underline the current line rather than highlighting the current line with a different background color, but only in terminal `vim` (`gvim` behavior seems unchanged).

**Seemingly relevant options:**
```vim
set cursorline
set termguicolors
let &t_8f = '\<Esc>[38;2;%lu;%lu;%lum'
let &t_8b = '\<Esc>[48;2;%lu;%lu;%lum'
let g:solarized_termtrans = 1
let g:solarized_extra_hi_groups = 1
colorscheme solarized8
```
I've also tried disabling these options to no effect.

**Other software:**
- `vim 8.1.1467`
- `termite v15`

**Previous/expected:**
![solarized-highlight](https://user-images.githubusercontent.com/124202/60269402-635fb100-98bc-11e9-9183-1bd1274ca0dd.png)

**Current:**
![solarized-underline](https://user-images.githubusercontent.com/124202/60269403-635fb100-98bc-11e9-8ba1-427132a570a2.png)

**Comment by lifepillar** [comment]
That's because you have set `g:solarized_termtrans`. When the background is transparent, the color of the cursor line may not blend well with the background, e.g.:
<img width="621" alt="solarized8_high_transpbg" src="https://user-images.githubusercontent.com/1193314/60291225-cbdd7b00-991a-11e9-90cd-379dca0072de.png">
vs
<img width="621" alt="solarized8_transpbg" src="https://user-images.githubusercontent.com/1193314/60291237-d435b600-991a-11e9-888d-3b0bc66b5b6f.png">

That's why I have made the change. Currently, only `solarized8_high` uses an opaque background for the cursorline when `g:solarized_termtrans` is set. Anyway, I will revert the change.

>I've also tried disabling these options to no effect.

Please check again. Cursorline is not underlined when `g:solarized_termtrans` is set to `0` (or not set). At least in `solarized8`: now that I'm checking, I see that the cursor line is not visible in `solarized8_flat` and `solarized8_low`, so that needs to be fixed.

>only in terminal vim (gvim behavior seems unchanged)

`g:solarized_termtrans` does not have any effect in gvim. GUIs have different ways to set a transparent background.

**Comment by lifepillar** [comment]
This should be fixed in the current master. Please reopen if that is not the case.

Thanks for reporting this!

**Comment by IrishPrime** [comment]
Looks like a step in the right direction, but it's still different from before (though, I understand that's part of the point). `g:solarized_termtrans` definitely has an effect (maybe I only changed it while I was on an older commit?), but it seems even stranger.

Trying to figure out if this background color is coming from somewhere else in my terminal config, but I'm using solarized colors pretty broadly and they look right everywhere else and I haven't been able to get this color to change.

Let me know if there's any other information I can provide.

*`g:solarized_termtrans = 1`
![solarized-transparent](https://user-images.githubusercontent.com/124202/60313705-27653400-992e-11e9-8df5-8eb39d01dfcd.png)

*`g:solarized_termtrans = 0`

![solarized-opaque](https://user-images.githubusercontent.com/124202/60313703-27653400-992e-11e9-9ff7-ed518d1c69a7.png)

**Comment by lifepillar** [comment]
I cannot reproduce it with my terminal (iTerm2). If you wrap strings in double quotes, does it change anything? I am referring to these lines:

```vim
    let &t_8f = '\<esc>[38;2;%lu;%lu;%lum'
    let &t_8b = '\<esc>[48;2;%lu;%lu;%lum'
```

What if you change it to:

```vim
    let &t_8f = "\<esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<esc>[48;2;%lu;%lu;%lum"
```

Your last screenshot looks strange: the status line has correct colors, but the rest is using the 256-color approximation.

**Comment by lifepillar** [comment]
Mmh, no, it's only a few colors that are off, the grey ones…

**Comment by IrishPrime** [comment]
Changing the quotes had no effect.

I've tried the color scheme in Mate Terminal and Terminator with similar results. I felt like I could rule out a local issue since it was previously working, but perhaps this is pointing to an issue with my `Xresources` defined colors or something. I feel like that gray just doesn't quite look like any of the grays in the solarized palette.

I'll keep poking at things and let you know if I figure anything out on my end. Perhaps I'm the only one encountering this.

**Comment by IrishPrime** [comment]
The gray in question is `#303030` according to my eyedropper tool. That's definitely not in the palette, but I also haven't been able to find it in any of my configuration files. Still, something for me to go on.

**Comment by lifepillar** [comment]
You said previous versions of Solarized 8 worked with your setup. Is that the case? If so, perhaps you could run a Git bisect to find the commit that introduced the issue.

**Comment by lifepillar** [comment]
>The gray in question is `#303030`

Then it's using the value of `ctermbg` which is ~`235`~ `236` (~`235`~ `236` is `#303030`). This may happen in Vim when `termguicolors` is set but the highlight group does not define `guibg`, in which case Vim falls back to using the value of `ctermbg`. What is the output of `:hi CursorLine`? Make sure that `termguicolors` is set before loading the color scheme.

**Edit:** fix typo.

**Comment by IrishPrime** [comment]
> Previous versions worked.

Yes.

> `git bisect`

That's how I first found it. Commit 97110edfc1ea68008783be4e91c1743436123e6d.

> `:hi CursorLine`

`CursorLine     xxx term=underline ctermbg=236 guibg=Grey40`

*Edit:* The colorscheme is the last line in my `.vimrc` other than the `modeline`.

**Comment by lifepillar** [comment]
>`CursorLine xxx term=underline ctermbg=236 guibg=Grey40`

This shouldn't happen if `termguicolors` is set before loading the color scheme. What are `:hi Normal` and, say `:hi Search`?

**Comment by lifepillar** [comment]
Even better, please run those commands with `verbose` (`:verbose hi Normal`) to see where they are set.

**Comment by IrishPrime** [comment]
Thank you! You figured it out.

> This shouldn't happen if `termguicolors` is set...

I wonder...

> `:set termguicolors?`
> `notermguicolors`

Well then. Apparently the conditional (visible in the screenshot) I have to set it is no longer returning true. Manually setting `termguicolors` and reapplying the colorscheme fixed it.

Closed. Resolved. Thanks for your effort, friend.

**Comment by lifepillar** [comment]
Good. You are not the first with this kind of issue. For an explanation of what has changed in the way Solarized 8 is built and the rationale behind it, you may read https://github.com/lifepillar/vim-gruvbox8/issues/11 (Gruvbox 8 is built in the same way).

This reinforces my opinion that the current approach with separate definitions for GUI and terminal is better, among the rest, because it highlights wrong configurations (pun intended).

**Comment by IrishPrime** [comment]
I very much agree. I take my `.vimrc` with me across a lot of different systems and not all of them have the same version of `vim` or even the same feature flags. Finding little things like this that aren't quite right is really helpful, because it will probably have other obscure net benefits down the road.
