### ISSUE TITLE
"Title" highlight group differs between dark and light

### ISSUE THREAD

**Issue by fladd** [lifepillar/vim-solarized8#76]
The highlight group "Title" is yellow (#b58900) in dark, and orange (#cb4b16) in light.

**Comment by fladd** [comment]
It's orange in both in the original Solarized.

**Comment by fladd** [comment]
It can even be seen on the screenshots for the project: https://camo.githubusercontent.com/ae89cd3f6dbe0c801291dc0450b9ad0cf7f6bf39/68747470733a2f2f7261772e6769746875622e636f6d2f6c69666570696c6c61722f5265736f75726365732f6d61737465722f736f6c6172697a6564382f736f6c6172697a6564382d76617269616e74732e706e67

**Comment by lifepillar** [comment]
If I recall correctly, I made the change for better readability.

I can’t stand red on blue; orange on blue is better, for for `Title` the contrast seemed a bit too low with dark background, so I changed to yellow.

Is this an issue for you?

**Comment by fladd** [comment]
Well, one of the main features (if not even **the** main feature) of the original Solarized is colour consistency across dark and light variants.
Solarized8 improves on the original Solarized in every other way, which is why the lack of this main feature is a rather noticeable.

> for Title the contrast seemed a bit too low with dark background, so I changed to yellow
Isn't the contrast of every colour the same to both the dark an light background in Solarized?

Anyway, switching colours for personal preferences (whatever they are) in itself is not the issue here (I saw that there are more changes than just "Title"), but then one would expect them to be switched in both dark and light variants in a consisten way. This would also make it easier for people to just change these colour preferences back to the original (or to some other personal preference) in their .vimrc. Even better would be an option in Solarized8 that automatically sets it to match the original Solarized colour choices (does not have to be the default).

Lastly, that particular colour change for "Title" creates another minor inconsistency with the "#" header symbols in Markdown in the dark variant, as is visible in your screenshots.

**Comment by lifepillar** [comment]
I'll try to address your concerns. But:

>one of the main features (if not even the main feature) of the original Solarized is colour consistency across dark and light variants. […] one would expect them to be switched in both dark and light variants in a consisten way.

I disagree that symmetry between dark and light variants is a feature. That assumes that human's eye response to colors is somewhat linear, but that is not the case. You cannot just “complement” a good pair of colors and hope that the result will look as good. Solarized's red against its light background is good enough (e.g., contrast ratio is 4.29), but Solarized's red against its dark background  is not so good (contrast ratio is 3.25).

As you have noticed, there are several subtle (or not so subtle) differences between dark and light variants of this color scheme. They exist because keeping symmetry in such cases would have produced an inferior result (for my eyes at least).

>Even better would be an option in Solarized8 that automatically sets it to match the original Solarized colour choices

I do not plan to add such an option, because it would increase the complexity of this already complex color scheme too much.

**Comment by lifepillar** [comment]
I have restored the original orange foreground for `Title` in the dark variant. Please check the current master.

**Comment by fladd** [comment]
>I disagree that symmetry between dark and light variants is a feature. That assumes that human's eye response to colors is somewhat linear, but that is not the case. You cannot just “complement” a good pair of colors and hope that the result will look as good. Solarized's red against its light background is good enough (e.g., contrast ratio is 4.29), but Solarized's red against its dark background is not so good (contrast ratio is 3.25).

Sorry, I think I wasn't clear here. I solely meant that this is an intended feature of the original Solairzed colour scheme. Whether that intention is desirable is of course an entirely different question, I agree with you.

> I have restored the original orange foreground for Title in the dark variant. Please check the current master.

Thanks, I appreciate it.

A small follow-up observation: When having set `g:solarized_visibility` to anything other than "normal", the colours are still different. Not sure if this is intended.

**Comment by lifepillar** [comment]
>When having set g:solarized_visibility to anything other than "normal", the colours are still different. Not sure if this is intended.

Yes, it is. With `"low"` visibility, titles are gray (less contrast) and with `"high"` visibility they are yellow (higher contrast). This gives users some choice. I might change `Special` to yellow, too, when visibility is `"high"`, so that Markdown titles have a uniform color, but if a user doesn't like the current appearance (in fact, I do like it), it is as easy for the user to link `markdownHeadingDelimiter` to `Title`.
